updateHash using this.type and this.request instead
this.request is JSON.stringified because otherwise an error will be thrown:
    TypeError: Data must be a string or a buffer

This is because the target ID may be string or number.