fixed [chunkhash] length regression
It's a fix for regression.

Regression was introduced in commit #4e041dfd52ec78187e57785a53d2e115712ae93c (issue #1181).

Also it fixes a previously broken test:

```
  1) ConfigTestCases hash-length output-filename should load additional chunks:
     Uncaught ENOENT, open '/home/travis/build/webpack/webpack/test/js/config/hash-length/output-filename/1.bundle.25a1b5a14f3986614a73.js'
  Error: ENOENT, open 'test/js/config/hash-length/output-filename/1.bundle.25a1b5a14f3986614a73.js'
      at Error (native)
```

(output from https://travis-ci.org/webpack/webpack/jobs/68229001)